apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: simple
  labels:
    env: eeshaans-env
    team: eeshaans-product
  input:
    manifests:
      - deployment.yaml
    kubectlVersion: 1.32.2