apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-advanced-v1
  labels:
    app: simple-advanced-v1
    env: example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-advanced-v1
  template:
    metadata:
      labels:
        app: simple-advanced-v1
    spec:
      containers:
        - name: simple-advanced-v1
          image: nginx:1.27.0
          ports:
            - containerPort: 80
          env:
            - name: WELCOME_MESSAGE
              value: "Hello from PipeCD!"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10